### ISSUE TITLE
Inputs not registering

### ISSUE THREAD

**Issue by Pritts** [OOPMan/XBOFS.win#16]
Thank you so much for creating this!
When i first followed the instructions, everything seemed to work but when i reconnected my madcatz XBO TE2 later on, it simply stopped registering the inputs.

It showed up in my device manager as 360 peripheral but no inputs register.

This is what shows up in XBOFS.win:
![image](https://user-images.githubusercontent.com/7469305/84067639-f60f3800-a9c7-11ea-8424-6688203f1963.png)

xbofs.win.qt5.txt log:

> [2020-06-08 21:51:16.349] [WinUsbDeviceManager] [info] Adding WinUsbDevice at \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}
> [2020-06-08 21:51:16.349] [WinUsbDeviceManager] [info] Sleeping for 1000 milliseconds
> [2020-06-08 21:51:16.349] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [info] Entered run()
> [2020-06-08 21:51:16.349] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [info] Connecting VigEmClient
> [2020-06-08 21:51:16.350] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [info] Adding VigEmTarget
> [2020-06-08 21:51:16.352] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [info] Starting Read-Process-Dispatch loop
> [2020-06-08 21:51:16.353] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [info] Opening WinUSB device
> [2020-06-08 21:51:16.361] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [info] Opened WinUSB device
> [2020-06-08 21:51:16.361] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [info] Init XBO Arcade Stick
> [2020-06-08 21:51:16.365] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [info] Reading input from XBO Arcade Stick

> [2020-06-08 21:51:47.727] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [warning] Failed to read input from XBO Arcade Stick
> [2020-06-08 21:51:47.727] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [warning] Failed to read input from XBO Arcade Stick 5 or more times for {}
> [2020-06-08 21:51:47.727] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [info] Opening WinUSB device
> [2020-06-08 21:51:47.727] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [error] Failed to open device handle due to -2147024894
> [2020-06-08 21:51:47.727] [WinUsbDevice \\?\USB#VID_0738&PID_4A01#000034CEAD63B27D#{5acf052a-3be5-46ae-905e-356ba17671bd}] [info] Opening WinUSB device

and multiple "Failed to open device handle due to -2147024894" and "opening WinUSB device"

**Comment by Pritts** [comment]
Seems like i have to uninstall the fightstick drivers and then reinstall the zading extracted drivers and it seems to work thereafter.

Is there anyway i can help you pin point the cause of this?

**Comment by Pritts** [comment]
Yeah, seems like whenever i reconnect, the inputs are no longer detected.

**Comment by OOPMan** [comment]
@Pritts Hi there, sorry for the delay in responding. It sounds like the ZaDig driver is being over-written. Can you add some screenshots of the device manager state with the ZaDig drivers installed and working and then also when it stops working?

**Comment by Pritts** [comment]
Sorry for my delay as well.
How do i do that?
@OOPMan

**Comment by Pritts** [comment]
I'm presuming this is what you're asking for. I'll go ahead and take some screenshots:

![image](https://user-images.githubusercontent.com/7469305/84473850-0e15de80-ac8a-11ea-8013-6efcc2dd733f.png)
^screenshot above is where it's working just fine.


![image](https://user-images.githubusercontent.com/7469305/84473966-47e6e500-ac8a-11ea-9ecf-38aa2d7528b9.png)
^And this one is when it's not working any longer.

It's odd that even the cursor for directional input has disappeared as well in second picture.

**Comment by OOPMan** [comment]
@Pritts Hmmmmm, that's really odd. Based on the log and the screen-shots, it seems like it is detecting the device but failing to read from it. Hmmmmmm. Unfortunately that error code doesn't help at all.

If you uninstall the drivers, reboot, reinstall the drivers, reboot and then test does the same thing happen?

**Comment by Pritts** [comment]
@OOPMan 
Yes same thing. Does not work, I can remove the fightstick drivers, unplug and plug the arcade stick back in, install drivers and then open up XBOFS.win.qt5, then it all works.

But as soon as I unplug the stick and plug it back in, it becomes unresponsive and I start with the previously mentioned steps.

**Comment by Pritts** [comment]
I don't know any C++, however I do have VS installed and if you'd like to use teamviewer or have this conversation over discord or some other means, you can debug it on my PC.

Just want to throw that offer, since I know other people have similar sticks and this would help them/myself immensely.

**Comment by OOPMan** [comment]
@Pritts Hmmmmm, are your friends with the same stick also experiencing this issue? I don't actually own a TE2 and was only able to add support thanks to a chap from France providing me with the device and vendor ID values. I haven't heard anything since from them so I have no clue if they're experiencing the same issue.

Could you check if your friends with the same stick experience the same issue. I have a suspicion is that the issue might be related to your system (I.e. weird driver store issues with Windows or something similar) rather than with the application as no one else has ever reported this issue and it can't see any specific reason this should be happening from the code side of things...

**Comment by Pritts** [comment]
@OOPMan Yes he has the same issue as I do.

I think we're doing similar things, where we have two drivers. One that's from 2014 and another that's from windows update.
2014 driver lets us see our inputs in "set up USB game controller"
Windows update one just crashes with a prompt "Your game controller is not connected properly, Please verify if the controller is plugged in properly"

By default, whenever i plugin after uninstalling zadig drivers, it selects the windows update drivers.
![image](https://user-images.githubusercontent.com/7469305/84535299-d8a1dd00-aceb-11ea-91d1-a6ed7b36ce6b.png)

**Comment by OOPMan** [comment]
@Pritts Hmmmmmmmmm, that's annoying. I'm going to have to refamiliarise myself with the code-base and development, I haven't actually be doing any work on the project for the last few months due to relocating and work. 

What timezone are you in? We can make a plan to try and use teamviewer after we've made sure I can actually debug remotely with your VS configuration...

**Comment by Pritts** [comment]
Denmark - GMT+2

Ah, wish I had found this plugin earlier so you didn't have to familiarize yourself all over again.
Thank you for taking your time to look into this.

**Comment by OOPMan** [comment]
Hmmmmmm, GMT+2, this is going to be tough :-(

I'm in Toronto (GMT-6) these days (I used to live in South Africa, also at GMT+2) which puts me about 8 hours behind you which is a problem because I can only really reliably find time to do a TeamViewer session after 22:00 on my end which is not really reasonable for you :-/

I might be able to find time on weekdays between 11:00 and 12:00 on weekdays next week (except for Thursday). Otherwise, if we can't sort out a workable time I'll have to put together some kind of guide to help you debug the issue further for me...

Oh, on a side note, could you test with https://github.com/OOPMan/XBOFS.win/releases/tag/v0.3a and see if it also has the issue. `03a` was the first version where I added TE2 support. It also predates the QT5 GUI mode for the application. If the issue with your stick is related to the GUI mode code then it should not happen with this older version. The documentation for this older version can be viewed here: https://github.com/OOPMan/XBOFS.win/blob/v0.3a/docs/index.md

**Comment by Pritts** [comment]
I am fine with 22:00, I can be up until 23:00 or 23:30. So we have one and a half hours window there.

I would like to have VS17 setup so it's ready, I'm seeing some problems with missing headers. I have not worked with C++ thus my knowledge on setting up proper environment is limited.

I cloned git and ran pre-build.cmd to add zadig submodule.
I opened up the solution but i'm getting following errors:
![image](https://user-images.githubusercontent.com/7469305/84565631-ac797100-ad6a-11ea-85c4-52c13c797de0.png)

And when trying to run, I run into some missing headers.
![image](https://user-images.githubusercontent.com/7469305/84565664-d92d8880-ad6a-11ea-9f63-b2e457eb18ef.png)
But i presume this is because i need the headers added to the project somehow.

I'lll give `03a` a go and see what happens.

**Comment by OOPMan** [comment]
@Pritts The project depends on Qt5 and you also need vcpkg installed, configured and to install spdlog using vcpkg

**Comment by OOPMan** [comment]
@Pritts FYI, when I said 22:00 I meant 22:00 at GMT-6. Which is about...04:00 for you? are you sure that's okay for you? 

I'm still sorting out my VS environment on this end, been a bit busy with other stuff unfortunately :-/

**Comment by OOPMan** [comment]
@Pritts Can you attack `c:\Windows\inf\setupapi.dev.log` to this ticket please

**Comment by Pritts** [comment]
Oh i see. Hmm that's a bit too early for me but i guess two hours later is too late for you.

Here you go:
[setupapi.dev.log](https://github.com/OOPMan/XBOFS.win/files/4778168/setupapi.dev.log)

**Comment by OOPMan** [comment]
@Pritts Thanks for the log. FYI, I updated the details in https://github.com/OOPMan/XBOFS.win/blob/master/README.md with regards to setting up VS for building the project. There was a lot of detail omitted but I updated it based on configuring my new system for developing on the project.

**Comment by Pritts** [comment]
Thanks a lot!
I'll try setting it up and getting it up and ready.
I was using VS17 so i'll have to update and get things sorted. I'll report back once I've finished setting up.

I guess easiest would be if you made a guide that i could follow to debug.

**Comment by OOPMan** [comment]
@Pritts I took a look at the log file but I can't see anything that stands out much. It looks like you've tried uninstalled and re-installing the driver a lot though.

Do you have another system that the driver has never been installed on that you could test with?

**Comment by Pritts** [comment]
I just tried on another PC and had same problem there.

Yea, that's the only way i can get it to work, by uninstalling and re-installed after unplugging.
Some work has come my way and I haven't gotten around to setting up yet.

**Comment by OOPMan** [comment]
@Pritts Okay, thanks for testing. I've also been busy with work. On my end I've been trying to see if I can get my hands on a TE2 XBO but they seem impossible to find (Except for a KI limited edition one...for $999 :-). 

I'm going to see what I can do about putting together some debugging instructions, I think I may have to do a custom branch of the code with enhanced logging and I may also ask you to do some USB debugging to make sure there aren't any issues with data packets.

Also, I assume the old version had the same issue?

**Comment by Pritts** [comment]
Sorry, had a bit of unfortunate couple of days.

Yes issues were exactly the same on older version
That's very steep price.
That sounds good to me. I'll try to finish setting up by tomorrow evening.

**Comment by OOPMan** [comment]
@Pritts Okay, there may be a bit of a delay in me getting debugging instructions, etc to you as I'm pretty busy with work stuff

**Comment by Pritts** [comment]
Thank you for taking your time to even look back at this.
I'll wait, i'm in no hurry.

**Comment by OOPMan** [comment]
@Pritts Heya, I thought I'd posted an update here but it seems not. Some notes:
- I updated the `master` branch so debug compiles work in VS2019
- The user that helped me implement TE2 support in the first place got back to me and confirmed that he too suffers from the issue. And not only that, it's been an issue from day one. I have no clue why he thought this was normal behavior. Regardless, it helps a bit.

Finally, can you attach your full `xbofs.win.qt5.txt log` file to this ticket. Or, better yet, if you can do the following:

0. Detach your TE2
1. Close XBOFS.win
2. Uninstall the ZaDig drivers
3. Remove `xbofs.win.qt5.txt log` and `c:\Windows\inf\setupapi.dev.log`
4. Reinstall the ZaDig drivers
5. Start XBOFS.win
6. Attach your TE2, wait 10 seconds
7. Detach your TE2, wait 10 seconds
8. Attach your TE2, wait 10 seconds
9. Attach the  `xbofs.win.qt5.txt log` and  `c:\Windows\inf\setupapi.dev.log` files in their new state

This should give me two log files with minimal white noise to trawl through.

**Comment by Pritts** [comment]
Hey @OOPMan 
I'll try to get that done. This heat is giving my kids a bad time and thus myself no time to concentrate.
I'll get back to you asap.
Thank you for updating the branch and giving me instructions.

**Comment by Pritts** [comment]
@OOPMan 
Sorry, I was very busy last week.

I've tried everything and tried resolving any and all dependency issues I've had, took a lot of time since i'm probably not doing everything correctly.

The only QT version that seem to compile this far is  "Qt\5.12.2\msvc2017"
![image](https://user-images.githubusercontent.com/7469305/86532194-3d55ef00-bec8-11ea-91ea-e3c6b1e2d7f9.png)

I'm not sure what to do here.
I applied pre_build.bat but i'm unsure if "VigEmClient.patch" was correctly applied.

**Comment by OOPMan** [comment]
@Pritts Okay, so the project is not configured to support 32-bit builds. When you start VS 2019 and open the solution things should look like this:

![image](https://user-images.githubusercontent.com/248980/86539574-a2f7aa80-becb-11ea-98c3-7e55931f167d.png)

Note the selected build is Debug and x64.

The only build configurations supported are Debug and Release compiling x64 binaries. As such, you'll need to use a `msvc2017_64` Qt package.

Additionally, how did you get the source? Did you check it out using Git or did you manually download the source zipfile from Github. If you did the latter you won't have all the source code, VigEmClient will be missing.

Additionally, the errors would seem to indicate you haven't installed the WDK. Did you follow the updated README with details on what versions of the Windows SDK and WDK to install?

For now, don't worry about compiling it manually. If you could just get me the log files as requested in the previous message using the release version that would be good. I want to check the timestamp correlation between messges in the two log files before anything else...

**Comment by Pritts** [comment]
I can only see "setupapi.dev" and not setupapi.dev.log
Here are both files:
[XBOFS.win.zip](https://github.com/OOPMan/XBOFS.win/files/4877838/XBOFS.win.zip)
They were too large so I had to compress them.

**Comment by Pritts** [comment]
@OOPMan Should i continue trying to setup a locally?

**Comment by OOPMan** [comment]
@Pritts Yeah, I think that's our only option. There's nothing in those logs indicating the specific issue I've been told can happen with WinUSB drivers.

**Comment by OOPMan** [comment]
@Pritts Hey, got some good news. I managed to get my hands on a TE2 (One of those Killer Instinct ones no less :-). This means I'll be able to debug the issue locally. Hopefully I can have some kind of fix done in the next few weeks :-) I'll give you a ping when there's something to test :-)

**Comment by Pritts** [comment]
@OOPMan Thank you so much for putting in this much effort and going to this length to address this issue!

I'll be keeping my eye on this.
I have not been able to spend any time getting my local environment up and running because of family.
I hope you're able to solve this issue!
Best of luck.

**Comment by OOPMan** [comment]
@Pritts Good news...I think I've fixed the issue.

Can you please head over to https://github.com/OOPMan/XBOFS.win/releases/tag/v0.4.1-rc1 and download the new `XBOFS.win.zip` archive to confirm the fix on your end. To test the update:

1. Exit any running instance of XBOFS.win
2. Extract the content of the new `XBOFS.win.zip` and replace the existing content
3. Start XBOFS.win
4. Test the TE2

My initial tests have so far been positive. I've done multiple replugs of the device and also tried between restarts of the application and everything seems good...

**Comment by Pritts** [comment]
@OOPMan Thanks a lot!
That's awesome!

I have one problem, my window opens up and disappears.
My settings were set to following:
![image](https://user-images.githubusercontent.com/7469305/88050061-747a0080-cb56-11ea-92b7-332911407d72.png)

So i'm guessing it minimizes it as soon as it starts and then does not add it to system tray
Is there a way for me to clear out my settings? lol

**Comment by Pritts** [comment]
On the other hand, it works!
Thank you for your time and everything you've done so far.
Is there any way I can donate coffee money to you?

**Comment by OOPMan** [comment]
@Pritts The settings are mostly stored in the registry. If you want to clear them out you can do the following:

0. Close XBOFS.win
1. Hit _Win+R_ to open the Run dialog
2. Input `regedit` and click _Okay_ or press enter
3. Input `Computer\HKEY_CURRENT_USER\Software\OOPMan\XBOFS.win` into the address bar in RegEdit
4. Right-click on the `XBOFS.win` item in the left pane and select the *Delete* item
5. Exit `regedit`
6. Hit _Win+R_ to open the Run dialog
7. Input `shell:startup` and click _Okay_ or press enter
8. An Explorer window will open containing your auto-start links. If there is a `XBOFS.win.qt5` item then delete it

No worries on the coffee money, the whole reason you were suffering from this issue was due to a stupid error in my code that wouldn't have existed in the first place if I had read the documentation on XBO controller protocol more closely. I'm just glad its sorted :-)
