### ISSUE TITLE
Analog Input Emulation

### ISSUE THREAD

**Issue by OOPMan** [OOPMan/XBOFS.win#18]
Implement support for generating analog output based on interpolating the directional input. Triggering this conversion process would probably best be handled by allowing the XBO Guide button to be pressed to toggle between analog and directional modes. Long-holding and releasing would trigger the usual XBO Guide functionality. Additionally, while in Analog mode, it might be possible to hold some other combination of buttons (E.g. Start + Select) to switch from left analog to right analog.

There are a couple of approaches that could be taken to this interpolation.

The simplest approach would be to simply convert the relevant direction to the maximum possible corresponding analog value. This is a very simple approach and can be implemented with minimal effort.

Another approach to would entail a little more configuration in the application by allowing the conversion from directional to analog to involve a time-delay aspect. With this approach, holding the directional input would cause the corresponding analog values to interpolate from neutral to a setpoint or maximum over a set period of time. Releasing the input could reverse this process over the same amount of time or immediately allow the analog value to revert to neutral. Implementing this more complex approach would most likely involve making use of the asynchronous approach to WinUSB communications.

It will probably be best to start with the simple implementation and then once that works well, start working on the more complex approach.

**Comment by jcwkroeze** [comment]
maybe look at rotors for doing the interpolation it's the hot new thing

**Comment by OOPMan** [comment]
> maybe look at rotors for doing the interpolation it's the hot new thing

Say what now? Link?

**Comment by jcwkroeze** [comment]
have a look at this https://marctenbosch.com/quaternions/

it's mostly about the 3D case but they work in 2D too
