### ISSUE TITLE
RESULT CODE -11 on Xbox One Razer Atrox DRIVER installation

### ISSUE THREAD

**Issue by 7RXN** [OOPMan/XBOFS.win#27]
i installed everything correctly on the instructions. when i need to install the driver for my razer atrox it fails to install. Giving me result code -11. i reinstall everything and nothing works

**Comment by OOPMan** [comment]
Did you have a working installation with the previous version?

**Comment by 7RXN** [comment]
I haven't thought of that, where could I find the previous version?

**Comment by 7RXN** [comment]
> Did you have a working installation with the previous version?

I haven't thought of that, where could I find the previous version?

**Comment by OOPMan** [comment]
No, I was asking because I wanted to know if you were upgrading or a first time user.

Okay, so there error you are having is something I saw once during testing. I wasn't able to work out the exact cause but I would recommend the following:

- Reboot
- Before using the Driver Manager
  - Exit all other programs where possible and make sure especially not to have the Windows Control Panel, or Device Manager applications open
  - Unplug any other controllers that may be attached
- Try the installation again

The one this happened when I was testing, the problem was resolved by rebooting and following the above process. Let me know if this works for you

**Comment by 7RXN** [comment]
> No, I was asking because I wanted to know if you were upgrading or a first time user.
> 
> Okay, so there error you are having is something I saw once during testing. I wasn't able to work out the exact cause but I would recommend the following:
> 
> * Reboot
> * Before using the Driver Manager
>   
>   * Exit all other programs where possible and make sure especially not to have the Windows Control Panel, or Device Manager applications open
>   * Unplug any other controllers that may be attached
> * Try the installation again
> 
> The one this happened when I was testing, the problem was resolved by rebooting and following the above process. Let me know if this works for you

I just attempted again and no success unfortunately. I did all you listed. Rebooted and tried again

**Comment by OOPMan** [comment]
Okay, then there is one more thing you can try, which is a manual installation of the driver. Try the following:

1. Make sure your fight stick is plugged in, the installation does not work if it is not plugged in
2. Make sure the XBOFS.win driver manager is not running and you can also close XBOFS.win as well to be sure
3. Navigate to the folder where XBOFS.win is installed
4. Look for the folder inside it named `zadig_driver`
5. Navigate into the `zadig_driver` folder
6. Look for the folder inside it that corresponds to your fight stick
7. Navigate into the the folder that correspond to your fight stick
8. Locate the file within the folder named either:
    * `razer_atrox_xbo.inf` if your stick is a Razer Atrox XBO
    * `madcatz_te2_xbo.inf` if your stick is a Madcatz TE2 XBO
9. Right-click on the file and click the `Install` item
10. You should get a message dialog indicating the driver installed

If you got an error message, let me know. If you got a success message, XBOFS.win should work...

**Comment by 7RXN** [comment]
> Okay, then there is one more thing you can try, which is a manual installation of the driver. Try the following:
> 
> 1. Make sure your fight stick is plugged in, the installation does not work if it is not plugged in
> 2. Make sure the XBOFS.win driver manager is not running and you can also close XBOFS.win as well to be sure
> 3. Navigate to the folder where XBOFS.win is installed
> 4. Look for the folder inside it named `zadig_driver`
> 5. Navigate into the `zadig_driver` folder
> 6. Look for the folder inside it that corresponds to your fight stick
> 7. Navigate into the the folder that correspond to your fight stick
> 8. Locate the file within the folder named either:
>     * `razer_atrox_xbo.inf` if your stick is a Razer Atrox XBO
>     * `madcatz_te2_xbo.inf` if your stick is a Madcatz TE2 XBO
> 9. Right-click on the file and click the `Install` item
> 10. You should get a message dialog indicating the driver installed
> 
> If you got an error message, let me know. If you got a success message, XBOFS.win

I got the pop up "operation completed" but the XBOFS.WIN didn't open up

**Comment by 7RXN** [comment]
> Okay, then there is one more thing you can try, which is a manual installation of the driver. Try the following:
> 
> 1. Make sure your fight stick is plugged in, the installation does not work if it is not plugged in
> 2. Make sure the XBOFS.win driver manager is not running and you can also close XBOFS.win as well to be sure
> 3. Navigate to the folder where XBOFS.win is installed
> 4. Look for the folder inside it named `zadig_driver`
> 5. Navigate into the `zadig_driver` folder
> 6. Look for the folder inside it that corresponds to your fight stick
> 7. Navigate into the the folder that correspond to your fight stick
> 8. Locate the file within the folder named either:
>     * `razer_atrox_xbo.inf` if your stick is a Razer Atrox XBO
>     * `madcatz_te2_xbo.inf` if your stick is a Madcatz TE2 XBO
> 9. Right-click on the file and click the `Install` item
> 10. You should get a message dialog indicating the driver installed
> 
> If you got an error message, let me know. If you got a success message, XBOFS.win should work...



YOOO man, it works!!! Thanks so much for all the time and help you gave man, seriously grateful, thanks a bunch dude!

**Comment by OOPMan** [comment]
@7RXN Glad to have helped, I'll update the docs and include details on this for anyone else that runs into the issue :-)
