### ISSUE TITLE
libwdi Result Code: -11

### ISSUE THREAD

**Issue by UINacho** [OOPMan/XBOFS.win#28]
Hello, I'm trying to install the driver for my Razer Atrox and I get libwdi Result Code: -11.

**Comment by OOPMan** [comment]
Hi @UINacho, can you try the instructions here: https://github.com/OOPMan/XBOFS.win/issues/27#issuecomment-885173279

**Comment by UINacho** [comment]
Thank you so much, it worked. Cheers.

**Comment by OOPMan** [comment]
Excellent!
