### ISSUE TITLE
Madcatz TE2 XBO (Killer Instinct version)

### ISSUE THREAD

**Issue by Lithrean** [OOPMan/XBOFS.win#29]
Got error libwdi Result Code: -11 when trying to install the driver.

**Comment by OOPMan** [comment]
See:
* https://github.com/OOPMan/XBOFS.win/issues/27
* https://xbofs.win/troubleshooting.html#when-i-try-to-install-the-winusb-driver-using-the-driver-manager-i-get-libwdi-result-code--11
