### ISSUE TITLE
Problem building solution using VS2019 and Qt

### ISSUE THREAD

**Issue by plbpietrz** [OOPMan/XBOFS.win#30]
Hi,

first of all thank you for your work regarding making Razer Atrox usable on Windows 10, this saved me sending the stick back 😄 . Being somewhat of a developer myself I wanted to dive a little bit deeper into the _ins and outs_ of the solution you provided. Not being versed in how Visual Studio is working I'm having difficulties building the project and to be exact how to incorporate Qt so that the IDE sees it. The DriverManager project doesn't load because of missing `XBOFS.win\DriverManager\QtMsBuild\Qt.props`, and other projects don't see the qt header files, so my question, how do you have your IDE setup with regards to Qt so that it's able to build 😄.
Best Regards.

**Comment by OOPMan** [comment]
@plbpietrz I'll take a look and try to add those files into the repo a little later today :-)

**Comment by OOPMan** [comment]
@plbpietrz Hmmmmm, it doesn't look like I have any `Qt.props` files in the whole project. Have you installed the Qt plugin for VS 2019?

**Comment by plbpietrz** [comment]
@OOPMan well, that's the peace of the equation that I was missing. Thank you for your help, now it's probably just few hours until it builds 🤣

**Comment by OOPMan** [comment]
@plbpietrz Excellent, so I can close this?

**Comment by plbpietrz** [comment]
This is a Widnows SDK 8.0 dependency?
`embedder : error : Could not open file 'C:\Program Files (x86)\Windows Kits\8.0\redist\wdf\x86\WdfCoInstaller01011.dll'.`

**Comment by OOPMan** [comment]
> This is a Widnows SDK 8.0 dependency?
> `embedder : error : Could not open file 'C:\Program Files (x86)\Windows Kits\8.0\redist\wdf\x86\WdfCoInstaller01011.dll'.`

Did you install the WDK?

**Comment by plbpietrz** [comment]
Yep, Windows Driver Kit 10.0.19041.685

**Comment by OOPMan** [comment]
Hmmmmmmmmmmm, this error is familiar to me. I'm pretty sure I ran into it, I'll do some looking and try to work out what I did to correct it. I think it's related to the library used by `DriverManager`

**Comment by OOPMan** [comment]
@plbpietrz Okay...from what I can tell it seems like the Windows 8 WDK is a dependency of `libwdi`. Can you try downloading the Windows 8 WDK from https://docs.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads and let me know if it fixes the issue. It looks like I may need to update my `README.md` :-)

**Comment by plbpietrz** [comment]
Ok, what was required was this one [WDK 8 redistributable components](https://go.microsoft.com/fwlink/p/?LinkID=253170). Now I'm looking at  a few of these `C:\[removed]\vcpkg\installed\x64-windows\include\spdlog\fmt\xchar.h(17,14): fatal error C1083: Cannot open include file: 'spdlog/fmt/bundled/xchar.h': No such file or directory (compiling source file main.cpp)`
Slowly but surely... :-)

**Comment by OOPMan** [comment]
> Ok, what was required was this one [WDK 8 redistributable components](https://go.microsoft.com/fwlink/p/?LinkID=253170). Now I'm looking at  a few of these `C:\[removed]\vcpkg\installed\x64-windows\include\spdlog\fmt\xchar.h(17,14): fatal error C1083: Cannot open include file: 'spdlog/fmt/bundled/xchar.h': No such file or directory (compiling source file main.cpp)`
> Slowly but surely... :-)

Hmmmmm, I haven't seen that one before. I wonder if the version of spdlog in vcpkg has changed...

**Comment by OOPMan** [comment]
@plbpietrz That header file is missing in my version. Can you check the contents of `vcpkg\installed\vcpkg\info` to see what version of `spdlog` is installed. Mine looks like so:

![image](https://user-images.githubusercontent.com/248980/153277936-9e05c3bf-1d41-489c-97ed-25f43fa9fe08.png)

**Comment by plbpietrz** [comment]
Well in my case I'm a little ahead with the versions:
- fmt:8.1.1
- spdlog:1.9.2

Will have to check if this compilation problem can be fixed simply or I'll revert. There were also some Qt related problems so I'll ask in advance what version do you use?

**Comment by OOPMan** [comment]
@plbpietrz Unfortunatley `vcpkg` makes it a bit hard to pick arbitrary versions. Hopefully you installed `vcpkg` by checking it out from Git? If that's the case, I'd suggest you do the following:

0. `cd path\to\vcpkg`
1. `git checkout 08214e18eeb146542944067c35d77faca8962be5`
2. `vcpkg remove spdlog:x64-windows fmt:x64-windows`
3. `vcpkg install spdlog:x64-windows`

This should download, compile and install the older versions required. Once that's done it the application will hopefully compile.

**Comment by OOPMan** [comment]
@plbpietrz Ah, I see you asked about Qt as well. The README is out of date on this as well, the application is now built against Qt 6.1.1

**Comment by OOPMan** [comment]
@plbpietrz Did you have any luck with the last two suggestions?

**Comment by plbpietrz** [comment]
Yep, the project built successfully on Qt 6.1.3 with the specific vcpkg version dependencies so thank you with that. Also found a possible buggy comparison between raw pointer address and value in WinUsbDeviceManager.cpp:143, shouldn't it go like this `...(*deviceInterfaceList) == TEXT('\0')`?

**Comment by OOPMan** [comment]
@plbpietrz You are correct it should be that. In fact, in the earlier code that came with the WinUSB sample it was correct (See https://github.com/OOPMan/XBOFS.win/blob/v0.1/RazorAtroxWinUSBVigEmFeeder/device.cpp#L214). It looks like when I was rewriting the application messed up that bit of code. It's kinda of interesting that it hasn't caused any problems although I'm guessing the if/else block combined with the first check in that line makes that the case.

**Comment by OOPMan** [comment]
@plbpietrz Thanks for digging up these issues. I'll update the README, fixed that comparison issue and also I think I may integrate the specific vcpkg requirements more directly via a git submodule with the specific version checked out to make it easier for fresh checkouts to build easily

**Comment by OOPMan** [comment]
Mostly resolved by https://github.com/OOPMan/XBOFS.win/pull/31

Just need to update the README
