### ISSUE TITLE
Razer Atrox XBO not working

### ISSUE THREAD

**Issue by chetanjags** [OOPMan/XBOFS.win#32]
While installing drivers for Razer atrox SBO i get error code -11.
![image](https://user-images.githubusercontent.com/3034986/158993906-224fed5f-3b19-4c2c-ae2d-470faa870330.png)

**Comment by OOPMan** [comment]
Please see https://xbofs.win/troubleshooting.html

This issue is covered there

**Comment by chetanjags** [comment]
Thanks for the quick response, it worked.
Thanks again for this project.

**Comment by OOPMan** [comment]
No problem
