### ISSUE TITLE
Failed trying to install a driver for Razer Atrox XBO Driver to use on Win11

### ISSUE THREAD

**Issue by ramonvalerio** [OOPMan/XBOFS.win#42]
My OS: Windows 11
Step to install:
1 - Execute, ViGEmBus_1.18.367_x64_x86.exe
2 - Execute, XBOFS.win.1.0.0.exe
3 - Execute, Win64OpenSSL-3_0_5.exe

The diagnostic error is:
libwdi Result Code: -11

**Comment by OOPMan** [comment]
See https://xbofs.win/troubleshooting.html

There is a section for this error code. Let me know if you have further issues after trying the suggested fixes there.
