### ISSUE TITLE
need a little bit of help

### ISSUE THREAD

**Issue by Alucardaria** [OOPMan/XBOFS.win#43]
libwdi result code: -12

**Comment by OOPMan** [comment]
Can you please provide some system specifications? According to libwdi that error code indicates it's not able to automatically install the drivers on your system.

Are you running 64-bit Windows?
Are you running on an x86 platform?

Any other system information would be useful

**Comment by Alucardaria** [comment]
im on 64 bit windows, i dont know much about computers so any other information you need lemme know

**Comment by OOPMan** [comment]
Windows 11, 10, 8 or 7?

Have you tried the manual driver installation instructions at https://xbofs.win/troubleshooting.html (See the section on libwdi error -11, the same solution may work)

**Comment by OOPMan** [comment]
Stale
