### ISSUE TITLE
libwdi Result code -11

### ISSUE THREAD

**Issue by breakfirez** [OOPMan/XBOFS.win#48]
sorry to bug you, but ive attempted to follow the troubleshooting for this specific issue and nothing in there seemed to fix my issue, im trying to use the razer atrox xbox one version, any help would be greatly appreciated

**Comment by OOPMan** [comment]
If you're still getting the error after trouble-shooting then there's not much I can do to help :-/

I can only suggest rebooting and trying the methods described in https://xbofs.win/troubleshooting.html again and making extra sure you've done what was described.

If you still have no luck then I guess you're one of the unlucky few for whome this application just doesn't work :-(

**Comment by breakfirez** [comment]
hey thanks for the quick reply, i gave it one last hail mary, restarting after every step, and i guess something went wrong on the first install because it didnt have any of the files/folders i did on the second install, still got the -11 error code but was able to install the file via the zadig folder and that solved everything, had a feeling the second after I made a post about the issue itd get solved, thanks a ton for even having this program as a workaround, really appreciate it
